version: "3"
services:
  db:
    image: camptocamp/postgis:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432"
  web:
    build: .
    depends_on:
      - db
    command: docker-compose run  --rm --service-ports web bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/lodging-map
      - bundle:/bundle
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_HOST=db
    dns:
      - 8.8.8.8
      - 8.8.4.4
volumes:
  db-data:
  bundle:

