version: "3"
services:
  db:
    image: camptocamp/postgis:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./environments/db.env
    ports:
      - "5432"
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/lodging-map/public
      - tmp-data:/lodging-map/tmp
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    depends_on:
      - db
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/lodging-map
      - bundle:/bundle
      - public-data:/lodging-map/public
      - tmp-data:/lodging-map/tmp
    env_file:
      - ./environments/db.env
volumes:
  db-data:
  bundle:
  public-data:
  tmp-data:
