db:
  image: mdillon/postgis:latest
  ports:
    - "5432"
  container_name: postgres-db
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  links:
    - db
  volumes_from:
    - datastore
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - DB_HOST=db
datastore:
  image: busybox
  volumes:
    - /bundle
